### ISSUE TITLE
Getting an error while starting retype

### ISSUE THREAD

**Issue by schtinkafinga** [retypeapp/retype#386]
Distro: fresh Debian 11 bullseye
ram: 1.5GB
disk: 10GB
installed with: npm

I get following error when trying to start retype:

```
root@md01:/home/wiki# retype run --verbose
  INPUT: /home/wiki
 OUTPUT: /home/wiki/.retype
 
Shutting down...
ERROR: Cannot assign requested address
System.Net.Sockets.SocketException (99): Cannot assign requested address
          at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError , String )
          at System.Net.Sockets.Socket.DoBind(EndPoint , SocketAddress )
          at System.Net.Sockets.Socket.Bind(EndPoint )
          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
       --- End of stack trace from previous location ---
          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
          at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
          at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
          at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
          at Retype.App.Server.RetypeServer.RunServerOnPortAsync(RunServerOnPortArgs args, CancellationToken cancellationToken)
          at Retype.App.Services.CliService.<CreateRunCommand>b__20_0(String host, Nullable`1 port, Boolean verbose, String path)
          at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
          at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
          at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at Retype.App.Services.CliService.<>c__DisplayClass23_0.<<CreateInfoOption>b__1>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Node.JS wrapper: resetting terminal cursor key and keypad modes.
Node.JS wrapper: exiting with status 1.
```

Retype works on another Ubuntu 20.04 server under same directory with all the .md files and etc

![img](https://user-images.githubusercontent.com/63101257/184545166-664c98b5-426f-4c83-95d2-ff9eeeb8d2c6.png)

**Comment by schtinkafinga** [comment]
up

**Comment by geoffreymcgill** [comment]
Are you trying to use the Retype built in development web server to host the generated website? If yes, it might be better to run `retype build` and then use another web server to host the generated website.
