### ISSUE TITLE
 On first start: System.IO.FileLoadException: Could not load file or assembly 'System.Linq.Expressions

### ISSUE THREAD

**Issue by legolego** [retypeapp/retype#425]
Hi,
I'm trying to install Retype on Bluehost(not a stand-alone vm) through the command line. It's a Linux system. I just installed nvm and node(version 10), went to my public_html directory and then to a directory with a sample .md file, and I run 'retype watch', but I get this error, which seems like it should be a Windows error, not Linux. Can you please let me know what I'm doing incorrectly? Thank you!

` prompt [~/www/retype]# retype watch
[Error]: System.IO.FileLoadException: Could not load file or assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
 (0x80070004)
File name: 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.CommandLine.IO.ConsoleExtensions.ResetTerminalForegroundColor(IConsole console)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<UseExceptionHandler>g__Default|14_1(Exception exception, InvocationContext context)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<CancelOnProcessTermination>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at Retype.App.Services.CliService.InvokeAsync(String[] args)
`

**Comment by geoffreymcgill** [comment]
What command did you install Retype with on the server?

**Comment by legolego** [comment]
npm install retypeapp --global

**Comment by geoffreymcgill** [comment]
Were there any warnings or errors written to the console when you installed Retype?

If I'm understanding correctly what you have configured, this doesn't really seem like it's required, nor a good idea. Any particular reason why you need to install Retype on your webserver?

Typically, Retype is run locally or on a continuous integration build server. The `output` of the project is then deployed to the webserver to be hosted.

**Comment by legolego** [comment]
Oh, I guess I didn't understand, I figured it needed to be on a web server, so that's where I tried installing it. So the 'retype watch' command compiles a self-contained `output` directory that then needs to be uploaded to a web server?

**Comment by geoffreymcgill** [comment]
You can install Retype locally on your dev machine and run the command `retype watch` which starts a local web server for testing. 

You can run the command [`retype build`](https://retype.com/guides/cli/#retype-build) to build the project and by default the generated website will be output to the `.retype` folder. That [`output`](https://retype.com/configuration/project/#output) location is of course customizable.

The contents of the `.retype` folder can be deployed to your web server.
