### ISSUE TITLE
Can't run retype

### ISSUE THREAD

**Issue by sunnystew22** [retypeapp/retype#428]
Hi, I get errors on any command I run.
`retype build`
Output VVV
`INPUT: C:\Users\[censored]
 OUTPUT: C:\Users\[censored\.retype
WARNING: [retype.yml] The "url" config should be set so Retype can generate a better sitemap and page meta tags.
ERROR: Failed to execute the command. Specify '--verbose' option for more detail.
System.UnauthorizedAccessException: Access to the path 'C:\Users\[censored]\Application Data' is denied.
          at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String , Boolean )
          at System.IO.Enumeration.FileSystemEnumerator`1.Init()
          at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String , Boolean , EnumerationOptions )
          at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 , Boolean )
          at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String , FindTransform , EnumerationOptions , Boolean )
          at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String , FindTransform , EnumerationOptions )
          at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String , String , EnumerationOptions )
          at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
          at Retype.App.IO.FileSystem.EnumerateDirectories(IDirectoryDescriptor parentDirectory, String searchPattern, SearchOption searchOption, String newBasePath)+MoveNext()
          at Retype.App.Jobs.InputDiscoveryJob.DiscoverInputs(InputDiscoveryJobArgs args, FilterRule[] rules, Int32& pageCount)
          at Retype.App.Jobs.InputDiscoveryJob.Run(InputDiscoveryJobArgs args)
          at Retype.App.Jobs.Job`2.RunAsync(TArgs args)
          at Retype.App.Jobs.Job`2.RunAsync(Object args, PipelineState state)
          at Retype.App.Pipelines.Pipeline`3.ExecuteAsync(TInitial initialValue, TState state)
          at Retype.App.Services.RetypeBuildService.DiscoverPagesAsync(Result assets, List`1 allBuildItems, IBuildOptions options, BuildStats stats)
          at Retype.App.Services.RetypeBuildService.BuildAsync(IBuildOptions options, Boolean verbose)
          at Retype.App.Services.CliService.BuildCommandHandler(Boolean verbose, IBuildOptions options, String path, String output, String secret, String overrideJson, String host, Nullable`1 port, Boolean isWatch, Boolean isRefresh, String hostUrl)
          at Retype.App.Services.CliService.<CreateBuildCommand>b__19_0(Boolean verbose, String output, String secret, String override, String path)
          at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
          at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
          at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at Retype.App.Services.CliService.<>c__DisplayClass23_0.<<CreateInfoOption>b__1>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
       --- End of stack trace from previous location ---
          at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by geoffreymcgill** [comment]
I'm not too sure what is going wrong here. Can you double check the command prompt where you are running `retype build` is correct and at the same location as your projects `retype.yml` file. 

You can check your current location with the `cd` or `pwd` command. If the current location is not correct, you can move to the correct path. 

If you run the command `retype watch`, does it build and run your project correctly?
